import type { Stage } from '@visactor/vtable/es/vrender';
import { Group } from '@visactor/vtable/es/vrender';
import { Grid } from './grid';
import type { Gantt } from '../Gantt';
import { ScrollBarComponent } from './scroll-bar';
import { TimelineHeader } from './timeline-header';
import { TaskBar } from './task-bar';
import { MarkLine } from './mark-line';
import { FrameBorder } from './frame-border';
import { TaskCreationButton } from './task-creation-button';
import { ToolTip } from './tooltip';
import { DependencyLink } from './dependency-link';
import { DragOrderLine } from './drag-order-line';
import type { GanttTaskBarNode } from './gantt-node';
export declare class Scenegraph {
    dateStepWidth: number;
    rowHeight: number;
    _scales: {}[];
    timelineHeader: TimelineHeader;
    grid: Grid;
    dependencyLink: DependencyLink;
    taskBar: TaskBar;
    _gantt: Gantt;
    ganttGroup: Group;
    scrollbarComponent: ScrollBarComponent;
    markLine: MarkLine;
    dragOrderLine: DragOrderLine;
    frameBorder: FrameBorder;
    taskCreationButton: TaskCreationButton;
    toolTip: ToolTip;
    stage: Stage;
    tableGroupWidth: number;
    tableGroupHeight: number;
    constructor(gantt: Gantt);
    initSceneGraph(): void;
    updateSceneGraph(): void;
    afterCreateSceneGraph(): void;
    refreshAll(): void;
    refreshTaskBars(): void;
    refreshTaskBarsAndGrid(): void;
    updateTableSize(): void;
    updateStageBackground(): void;
    renderSceneGraph(): void;
    updateNextFrame(): void;
    get width(): number;
    get height(): number;
    get x(): number;
    get y(): number;
    setX(x: number, isEnd?: boolean): void;
    setY(y: number, isEnd?: boolean): void;
    setPixelRatio(pixelRatio: number): void;
    resize(): void;
    release(): void;
    showTaskCreationButton(x: number, y: number, dateIndex: number): void;
    hideTaskCreationButton(): void;
    showToolTip(target: any): void;
    hideToolTip(): void;
    refreshRecordLinkNodes(taskIndex: number, sub_task_index: number, target: GanttTaskBarNode, dy?: number): void;
}
