export declare function throttle(func: Function, delay: number): (this: any, ...args: any[]) => void;
export declare function throttle2(func: Function, delay: number): (this: any, ...args: any[]) => void;
export declare function getTodayNearDay(dayOffset: number, format?: string): string | Date;
export declare function formatDate(date: Date, format: string): string;
export declare function parseDateFormat(dateString: string): string;
export declare function parseStringTemplate(template: string, data: any): string;
export declare function toBoxArray<T>(obj: T | T[]): [T, T, T, T];
export declare function getWeekNumber(currentDate: Date): number;
export declare function getWeekday(dateString: string | Date, format?: 'long' | 'short'): string;
export declare function isPropertyWritable(obj: any, prop: string | number): boolean;
export declare function createDateAtMidnight(dateStr?: string | number | Date, forceMidnight?: boolean): Date;
export declare function createDateAtLastMinute(dateStr?: string | number | Date, forceSetMinute?: boolean): Date;
export declare function createDateAtLastSecond(dateStr?: string | number | Date, forceSetSecond?: boolean): Date;
export declare function createDateAtLastMillisecond(dateStr?: string | number | Date, forceSetMillisecond?: boolean): Date;
export declare function createDateAtLastHour(dateStr?: string | number | Date, forceLastHour?: boolean): Date;
export declare function getEndDateByTimeUnit(startDate: Date, date: Date, timeScale: 'day' | 'week' | 'month' | 'quarter' | 'year' | 'hour' | 'minute' | 'second', step: number): Date;
export declare function getStartDateByTimeUnit(date: Date, timeScale: 'day' | 'week' | 'month' | 'quarter' | 'year' | 'hour' | 'minute' | 'second', startOfWeekSetting?: string): Date;
export declare function computeCountToTimeScale(date: Date, startDate: Date, timeScale: 'day' | 'week' | 'month' | 'quarter' | 'year' | 'hour' | 'minute' | 'second', step: number, diffMS?: number): number;
export declare function parseDateToTimeUnit(date: Date, timeUnit: 'day' | 'week' | 'month' | 'quarter' | 'year' | 'hour' | 'minute' | 'second'): number;
